'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("windows_95.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _16_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1994_mclaren_f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1994-mclaren-f1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _256_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("256 color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chat__32x32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat (32x32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chat__big_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat (big)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property energysave_windows_95() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("energysave windows 95", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_blast__big_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_blast__big_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ErrorBlast__One_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorBlast (One)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property googlebetalogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("googlebetalogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property googleprotoype() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("googleprotoype", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guess_the_Number__install_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guess_the_Number__install_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guess_the_number_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guess the number Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guess_the_number_number_1__32x32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guess the number number 1 (32x32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property high_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("high color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmail_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmail logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmail_signup_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmail signup button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmail_slogan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmail slogan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmail2ndfromtopbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmail2ndfromtopbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmailcirclearrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmailcirclearrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmailside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmailside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmailtop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmailtop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hotmailwhysignup_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hotmailwhysignup button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property install_icon__32x32__basic__liquify_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("install icon (32x32) basic (liquify)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mini_applications_window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini applications window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property programs_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("programs icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property programs_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("programs icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Run_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowdirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowdirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindows_95__install_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindows 95 (install)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindows_95_picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindows 95 picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsbinary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsbinary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsconcrete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsconcrete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsfirebar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsfirebar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsfirebar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsfirebar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsfirebar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsfirebar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsgrassbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsgrassbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowslightingbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowslightingbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsskybar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsskybar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsskybar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsskybar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowsskybar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowsskybar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skindowswaterbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skindowswaterbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_button_windows_95() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start button windows 95", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_run__32x32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start run (32x32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_run__install___white_with_programname_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start_run__install___white_with_programname_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suspend_pic_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suspend pic start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suspend_pic_start1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suspend pic start1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Time_Distorter_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Time Distorter icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property true_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("true color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows_95_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows 95 background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows_95_settings_computer_example() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows 95 settings computer example", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows_95_sidemenustart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows 95 sidemenustart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookactionblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookactionblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookdeleteblackandwhiteicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookdeleteblackandwhiteicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookdeleteblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookdeleteblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookfindpeopleblackandwhiteicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookfindpeopleblackandwhiteicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookfindpeopleblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookfindpeopleblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbooknewblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbooknewblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookprintblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookprintblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookpropertiesblackandwhiteicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookpropertiesblackandwhiteicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95addressbookpropertiesblackandwhiteicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95addressbookpropertiesblackandwhiteicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95adressbookstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95adressbookstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95aolandinternetfreetrial_startmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95aolandinternetfreetrial!startmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95atandtworldsignupstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95atandtworldsignupstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95bootsound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windows95bootsound", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property windows95calcualatorstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95calcualatorstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95cdplayerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95cdplayerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95controlpanelstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95controlpanelstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95diskdefragmentorstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95diskdefragmentorstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95dosstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95dosstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95findcomputerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95findcomputerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95findfilesorcomputersstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95findfilesorcomputersstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95findontherinternetstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95findontherinternetstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95findpeoplestartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95findpeoplestartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95hyperterminalstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95hyperterminalstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95imagingstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95imagingstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetconnectionwizardstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetconnectionwizardstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerfavorites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerfavorites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerforward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerforward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorergobutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorergobutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerhistory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerhistory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerhome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerhome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerrefresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerrefresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorerstop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorerstop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95internetexplorertoplogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95internetexplorertoplogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95mediaplayerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95mediaplayerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95netmeetingstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95netmeetingstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95notepadstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95notepadstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95onlineregistrationstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95onlineregistrationstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95outlookexpressstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95outlookexpressstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95painbrush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95painbrush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95painoval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95painoval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintbrushpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintbrushpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintcolorpick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintcolorpick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintcolorselectpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintcolorselectpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintcurvyline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintcurvyline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintcurvylinepress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintcurvylinepress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95painteracer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95painteracer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintfill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintfill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintfillpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintfillpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintfreeselectoricon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintfreeselectoricon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintfreeselectpush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintfreeselectpush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintlinepress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintlinepress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintmagnifypress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintmagnifypress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintovelpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintovelpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintpencil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintpencil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintpencilpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintpencilpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintpolygon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintpolygon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintpolygonepress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintpolygonepress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintrectangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintrectangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintrectangleselector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintrectangleselector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintrectangleselectpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintrectangleselectpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintroundedcircle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintroundedcircle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintrubberpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintrubberpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintspraycanpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintspraycanpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95paintstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95paintstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95painttext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95painttext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95painttextpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95painttextpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95phonedialerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95phonedialerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95printersstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95printersstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95rectanglepress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95rectanglepress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95roundedrectanglepress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95roundedrectanglepress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95runicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95runicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95scandiskstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95scandiskstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95setupcomuservicestartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95setupcomuservicestartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95setupwowstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95setupwowstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95soundrecorderstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95soundrecorderstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95speakerleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95speakerleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95speakerright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95speakerright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95spraycan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95spraycan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95taskbarstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95taskbarstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95volumecontrolstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95volumecontrolstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95windowsexplorerstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95windowsexplorerstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95wordpadstartmenuicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95wordpadstartmenuicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows95zoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows95zoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98bootsound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windows98bootsound", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property windows98logoffscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98logoffscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmendisccleanup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmendisccleanup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenuamericaonline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenuamericaonline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenucompuserve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenucompuserve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenudialupnetworking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenudialupnetworking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenudriveconvert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenudriveconvert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenufavorites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenufavorites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenumaintanecewizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenumaintanecewizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenupersonwebserver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenupersonwebserver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenuprodigyinternet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenuprodigyinternet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenusampler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenusampler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenusampler1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenusampler1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenuscedualed_tasks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenuscedualed tasks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenusidelogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenusidelogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenusysteminformation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenusysteminformation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenuupdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenuupdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows98startmenuwelcometowindows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows98startmenuwelcometowindows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
